# syntax=docker/dockerfile:1

FROM ruby:4.0.1-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential python3 python3-venv ffmpeg && \
    python3 -m venv /usr/local/essentia-venv && \
    /usr/local/essentia-venv/bin/pip install --no-cache-dir "essentia-tensorflow==2.1b6.dev1389" && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV PATH="/usr/local/essentia-venv/bin:${PATH}"

WORKDIR /sonance
COPY . .
RUN bundle install
